# This is a basic workflow to help you get started with Actions

name: Build & Deploy
on:
  push:
    branches:
      - staging
      - prod
       # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  APP_NAME: ${{ secrets.APP_NAME }}
  STAGING_TEMPLATE_API: https://staging-api.covault.app
  PRODUCTION_TEMPLATE_API: https://prod-api.covault.app
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
           
          if [ "${BRANCH}" = "staging" ]; then
            echo ${env.STAGING_TEMPLATE_API}
           
          elif [ "${BRANCH}" = "prod" ]; then
            echo ${env.PRODUCTION_TEMPLATE_API}
  
